"""Add Test Column in Courses Table

Revision ID: 6820811523b3
Revises: c768640b8a7c
Create Date: 2022-08-10 20:36:32.497763

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6820811523b3"
down_revision = "c768640b8a7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("test", sa.String(), nullable=True))
    op.drop_constraint("course_module__fkey", "course", type_="foreignkey")
    op.drop_constraint("course_subject_id_fkey", "course", type_="foreignkey")
    op.create_foreign_key(
        None, "course", "subject", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "course", "module", ["module_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "job_title", existing_type=sa.VARCHAR(length=150), nullable=False
    )
    op.alter_column("user", "is_super_user", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("user", "is_super_user", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "user", "job_title", existing_type=sa.VARCHAR(length=150), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_constraint(None, "course", type_="foreignkey")
    op.drop_constraint(None, "course", type_="foreignkey")
    op.create_foreign_key(
        "course_subject_id_fkey", "course", "subject", ["subject_id"], ["id"]
    )
    op.create_foreign_key(
        "course_module__fkey", "course", "module", ["module_id"], ["id"]
    )
    op.drop_column("course", "test")
    # ### end Alembic commands ###
