"""Remove Test Column in Courses Table

Revision ID: efc225014398
Revises: 6820811523b3
Create Date: 2022-08-10 20:40:49.645360

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efc225014398"
down_revision = "6820811523b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("test", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
